name = "pngleam"
version = "1.1.1"

description = "PNG image library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "LilyRose2798", repo = "pngleam" }
links = [
  { title = "Whitespace Git", href = "https://whitespace/lily/pngleam" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gzlib = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
